name: deploy
# 이 워크플로우는 Jekyll을 사용하여 정적 웹사이트를 빌드하고 GitHub Pages에 자동으로 배포하는 것이다.
on: # 특정 이벤트 발생
  push: # push 하는 상황
    branches:
      - master
      - main
  pull_request: # pull_request 하는 상황
    branches:
      - master
      - main
  workflow_dispatch: # 사용자가 수동적으로 workflow를 실행하려고 할 때

permissions:
  contents: write # 해당 액션이 디렉토리에 쓰기 권한을 가짐을 명함.

jobs: # 주된 내용들
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout 🛎️
      uses: actions/checkout@v4 # 👈 1. 버전을 v4로 변경 (Node.js 경고 해결)
      
    - name: Setup Ruby 
      uses: ruby/setup-ruby@v1 
      with:
        ruby-version: '2.7.5'
        bundler-cache: true 
        
    - name: Update _config.yml ⚙️
      uses: fjogeleit/yaml-update-action@main # 👈 2. 버전을 main으로 변경 (Node.js 경고 해결)
      with:
        commitChange: false
        valueFile: '_config.yml' 
        propertyPath: 'giscus.repo' 
        value: ${{ github.repository }} 
        
    - name: Install and Build 🔧
      run: | 
        pip3 install --break-system-packages --upgrade jupyter # 👈 3. --break-system-packages 추가 (exit code 1 에러 해결)
        npm install -g mermaid.cli
        npm install -g purgecss
        export JEKYLL_ENV=production
        bundle exec jekyll build --lsi
        purgecss -c purgecss.config.js
        
    - name: Deploy 🚀
      if: github.event_name != 'pull_request' 
      uses: JamesIves/github-pages-deploy-action@v4 
      with:
        folder: _site
